services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  goapp:
    build:
      context: goapp
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - grafana
  effectapp:
    build:
      context: effectapp
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    depends_on:
      - grafana

volumes:
  grafana-storage: {}
